# Generated by Django 2.1.4 on 2019-01-04 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarizer',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
